// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcxvgjdtgoejkfvcpscg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjeHZnamR0Z29lamtmdmNwc2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MDc0NTIsImV4cCI6MjA3MDI4MzQ1Mn0.MCVNUn6DEUpCbki87reIhVARWUI6oz1ZixaqoIR9eN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});